[project]
name = "count-down-timmer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "playsound>=1.3.0",
    "win10toast>=0.9",
]
